apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership-image
  name: dealership-image
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership-image
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership-image
    spec:
      containers:
      - image: us.icr.io/hemanth-dallas-namespace/dealership-image:latest
        imagePullPolicy: Always
        name: dealership
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always