apiVersion: v1
kind: Service
metadata:
  name: dealership-service
  namespace: default
spec:
  selector:
    app: dealership
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
